---
title: "R Notebook"
output: html_notebook
---

```{r lib, include=FALSE}
library(lme4)
library(car)
library(knitr)
library(dplyr)
library(ggplot2)
#library(ggpmisc)
library(ggsignif)
library(stringr)
library(data.table)
library(fitdistrplus)
library(corrplot)
library(performance)
library(lmerTest)
```

Calculate models at frame level for all files found in frame_tables folder

```{r}
# load paths
resultsPath = '/hdd/ReposPesados/SaliencyADHD/notebooks/results/WK/'
tableName = 'table_Diary_'
# for each table file run an lmer model and save summary
csv_files = list.files(paste(resultsPath,'frame_tables/',sep=""), pattern = ".csv") 
for (file in csv_files){
    DAVG <- readDataTable(resultsPath, paste('frame_tables/',file,sep=""))
    #Por ahora trabajo con los putliers incluidos
    #DAVG <- removeOutliers(DAVG, video)
    DAVG <- DAVG[DAVG$ADHDCategory != "OtherDx", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-OS", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-US", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-HI", ]
    DAVG$ADHDCategory <- droplevels(DAVG$ADHDCategory)
    DAVG$ADHDCategory <- relevel(DAVG$ADHDCategory, ref = "NoADHD")
    DAVG$ID <- as.factor(DAVG$ID)
    D.fg <- DAVG
    D.fg <- D.fg[ , !(names(D.fg) %in% c("NSS_vn"))]
    names(D.fg)[names(D.fg) == 'NSS_fg'] <- 'NSS'
    D.fg$SemLevel <- 0
    D.vn <- DAVG
    D.vn <- D.vn[ , !(names(D.vn) %in% c("NSS_fg"))]
    names(D.vn)[names(D.vn) == 'NSS_vn'] <- 'NSS'
    D.vn$SemLevel <- 1 
    DF <- rbind(D.fg, D.vn)
    DF$ADHDCategory <- as.factor(DF$ADHDCategory)
    DF$SemLevel <- as.factor(DF$SemLevel)
    m.cat <- lmer(NSS ~ Age + Sex + IQ + EHQ_Total + samplingRate + ADHDCategory * SemLevel + (1|ID), data=DF, na.action = na.omit)
    aux <- summary(m.cat)$coefficients
    summary(aux)
    write.csv(aux, paste(resultsPath, 'frame_models/', file ,sep=""))
}
```

Calculate models at scene level for all files found in scene_tables folder

```{r}
# load paths
resultsPath = '/hdd/ReposPesados/SaliencyADHD/notebooks/results/WK/'
tableName = 'table_Diary_'
# for each table file run an lmer model and save summary
csv_files = list.files(paste(resultsPath,'scene_tables/',sep=""), pattern = ".csv") 
for (file in csv_files){
    DAVG <- readDataTable(resultsPath, paste('scene_tables/',file,sep=""))
    #Por ahora trabajo con los putliers incluidos
    #DAVG <- removeOutliers(DAVG, video)
    DAVG <- DAVG[DAVG$ADHDCategory != "OtherDx", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-OS", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-US", ]
    DAVG <- DAVG[DAVG$ADHDCategory != "ADHD-HI", ]
    DAVG$ADHDCategory <- droplevels(DAVG$ADHDCategory)
    DAVG$ADHDCategory <- relevel(DAVG$ADHDCategory, ref = "NoADHD")
    DAVG$ID <- as.factor(DAVG$ID)
    D.fg <- DAVG
    D.fg <- D.fg[ , !(names(D.fg) %in% c("NSS_vn"))]
    names(D.fg)[names(D.fg) == 'NSS_fg'] <- 'NSS'
    D.fg$SemLevel <- 0
    D.vn <- DAVG
    D.vn <- D.vn[ , !(names(D.vn) %in% c("NSS_fg"))]
    names(D.vn)[names(D.vn) == 'NSS_vn'] <- 'NSS'
    D.vn$SemLevel <- 1 
    DF <- rbind(D.fg, D.vn)
    DF$ADHDCategory <- as.factor(DF$ADHDCategory)
    DF$SemLevel <- as.factor(DF$SemLevel)
    m.cat <- lmer(NSS ~ Age + Sex + IQ + EHQ_Total + samplingRate + ADHDCategory * SemLevel + (1|ID), data=DF, na.action = na.omit)
    aux <- summary(m.cat)$coefficients
    summary(aux)
    write.csv(aux, paste(resultsPath, 'scene_models/', file ,sep=""))
}
```
